# Generated by Django 4.1.4 on 2022-12-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_variants', to='quiz.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='variant',
            field=models.ManyToManyField(related_name='quiz_correct_answer', to='quiz.answer'),
        ),
    ]
