name: CI-CD
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose build --no-cache
      - run: docker-compose up -d
      - run: docker-compose stop