name: CI-CD
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: easingthemes/ssh-deploy@main

    env:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      REMOTE_HOST: ${{ secrets.HOST_DNS }}
      REMOTE_USER: ${{ secrets.USERNAME }}
      TARGET: ${{ secrets.TARGET_DIR }}